theme: jekyll-theme-minimal
title: Benjamín Maturana Durán
description: Repositorio de Benjamín Maturana Durán. Incluye las resoluciones de las tareas realizadas para la Unidad 1 y Unidad 2 del curso Programación Avanzada. Además, una página web del autor con formato de CV, resumiendo su carrera académica, profesional y laboral.
